# Configuration template. All values shown are defaults.
# Uncomment and modify as needed. CLI args override values set here.

commons:
  # nbThreads: 1
  # distribute: 1
  # tmp_path: ./tmp
  # fileLogLevel: error
  # screenLogLevel: error
  # keeptmp: false

tile_and_convert_pcl:
  # infile: null
  # outdir: null
  # nbThreads: 1
  # distribute: 1
  # tileSize_odm: 24.0
  # tmp_path: ./tmp
  # pointOrigin: null
  # tileSize: 500
  # keepodm: true
  # buffer: 0
  # keeptmp: null

tac_raster:
  # infile: null
  # outdir: null
  # minTileSize: null
  # tileSize: 16384
  # skipIfExists: true
  # compress: DEFLATE
  # blockSize: 512
  # overviews: AUTO
  # nbThreads: ALL_CPUS
  # bigTiff: IF_SAFER
